### ISSUE TITLE
How to preserve the original sound

### ISSUE THREAD

**Issue by asasas234** [thurti/vad-audio-worklet#1]
Hello, I would like to ask a question.

I want to mute the audio when human voice is detected, and keep the input sound unchanged and output it as it is when no human voice is detected.

I tried modifying the example given in the readme file. I have put the code below
```
source.connect(vad)
```
Modified to
```
source.connect(vad).connect(audioContext.destination);
```
Then I tried to add the following code at the entrance of the process method in vad-audio-worklet.js
```
     for (let channel = 0; channel < this.outputChannelCount; channel++) {
       outputs[0][channel].set(inputs[0][channel]);
     }
```
However, I found that there would be a lot of noise. How to simply replace the process method with the following code so that there will be no noise
```
  process(inputs, outputs, parameters) {
    for (let channel = 0; channel < this.outputChannelCount; channel++) {
      outputs[0][channel].set(inputs[0][channel]);
    }
    return true
  }
```
I would like to ask, how can I fix this issue? I want to achieve the function of muting when detecting human voice, and outputting the original audio without noise when there is no human voice.

Thank you very much for developing this project. Looking forward to your reply.

**Comment by thurti** [comment]
Mh, `return true` at the beginning of `process()` will actualy disable the vad algorithm and only pass through the audio data. All code after the return statement will not be executed. 

So this means the noise gets introduced by the algorithm, I guess.? I wonder how, since the values get copied over into the buffer `this.buffer.push(...inputs[0][0]);` to prevent that they get altered. 

Can you post a minimal working example that produces the noise?

**Comment by asasas234** [comment]
@thurti Currently, I have made modifications to the code and found that by placing the following code above `if (this.buffer.length < this.frame_size) {`, the noise issue is resolved. Therefore, I speculate that the noise is caused by the buffer not being full yet.
```
 for (let channel = 0; channel < 1; channel++) {
      outputs[0][channel].set(inputs[0][channel]);
    }
```

**Comment by asasas234** [comment]
@thurti But I encountered a new problem, which is that when detecting human voice and preparing to emit the speech event, I hope to modify all outputs to 0 in order to achieve a mute effect. The code is as follows:
```
    if (this.is_speech_frame_counter > 4 && !this.last_command_was_speech) {
      for (let channel = 0; channel < inputs[0].length; channel++) {
        inputs[0][channel].fill(0);
      }
      if (this.debug) {
        this.post("speech", { signal: sfm_sum_ari / frequencyData.length });
      } else {
        this.post("speech");
      }

      this.last_command_was_speech = true;
    }
```

However, I found that it doesn't seem to work. When playing the video, I can still hear the voices inside.

**Comment by asasas234** [comment]
@thurti  But I encountered a new problem. I want to fill all the data in the output with 0 when detecting human voice, that is, when the speech event is about to occur, in order to achieve silence effect. However, it doesn't work at all in reality and I can still hear voices.
```
    if (this.is_speech_frame_counter > 4 && !this.last_command_was_speech) {
      for (let channel = 0; channel < 1; channel++) {
        outputs[0][channel].fill(0);
      }
      if (this.debug) {
        this.post("speech", { signal: sfm_sum_ari / frequencyData.length });
      } else {
        this.post("speech");
      }

      this.last_command_was_speech = true;
    }
```

**Comment by asasas234** [comment]
@thurti I think it may be wrong to use the vad method to remove human voices from videos in a browser, because looking at the code, the vad method seems to work like a recorder, needing to play out some of the human voice before detecting whether there is human voice in the audio. Because it's recording, that's why there's that buffer, which doesn't seem to match my needs. However, I think you have more experience in web audio and still want to ask for advice. Is there any way or idea to remove human voices from videos in a browser?

**Comment by thurti** [comment]
You're right. The algorithm needs some time before it can decide if the audio is voice. The buffer is 10ms (1 frame) and the algorithm needs several of these frames to decide.

Your code above doesn't work because this vad works more like a state change. The algorithm checks each 10ms frame and only if 5 consecutive frames are detected as speech the "state" switches to "speech" (until silence gets detected again). You can try to check for `this.last_command_was_speech` and then set your audio to zero at the top of the `process()` method.

```
 if (this.last_command_was_speech) {
      for (let channel = 0; channel < 1; channel++) {
        outputs[0][channel].fill(0);
      }
 }
```

But this "state" switches very often. And zero out samples may lead to audible clicks. You propably need to implement an additional buffer for your audio to smooth things out. Keep the last n samples and decide what to do when you get a "state" change from the vad. I've done smth similar [here](https://github.com/TranscribeJs/transcribe.js/blob/410d2bc9b9aa01ac4e887503787cbf817cde2510/src/StreamTranscriber.js#L249), but I'm actually not sure if this is a good solution to this :D .

Apart from that this vad algorithm isn't the best tbh. It is good enough for my use case, but in tests I often got false (speech) positives. So even if you get this to work the result may not be reliable.

Maybe have a look at https://github.com/ricky0123/vad . I've only tried the demo but it seems pretty good. And it also got a lot of options like prepend audio and you also get the detected speech as array buffer.

**Comment by asasas234** [comment]
@thurti Thank you very much for your response. I took a look at https://github.com/ricky0123/vad and found that it is also not suitable for my use case because it uses onnx at the lower level. I briefly looked at Onnx, tensorFlow.js, and transformer.js, and found that they all require asynchronous execution, while audioworkletprocessor requires a synchronous interface.

It seems that this problem is difficult to solve, so I am considering giving up...

**Comment by thurti** [comment]
Yes, it's definitely more complicated than it looks at first glance. 
I will add some more information in the readme about what to expect from this vad implementation.
